insert into public.product_inventory (
  product_code,
  product_name,
  image_url,
  available_quantity,
  reserved_quantity,
  is_active
)
values
  ('ve001', 'Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/001.png', 10, 0, true),
  ('ve002', 'Jeff the Land Shark', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/002.png', 10, 0, true),
  ('ve003', 'Private Detective', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/003.png', 10, 0, true),
  ('ve004', 'Vermin', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/004.png', 10, 0, true),
  ('ve005', 'Spider-Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/005.png', 10, 0, true),
  ('ve006', 'Symbiote Soldier', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/006.png', 10, 0, true),
  ('ve007', 'Carnage', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/007.png', 10, 0, true),
  ('ve008', 'Zombiote', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/008.png', 10, 0, true),
  ('ve009', 'Hive', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/009.png', 10, 0, true),
  ('ve010', 'Black Widow', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/010.png', 10, 0, true),
  ('ve011', 'Venom-Bot', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/011.png', 10, 0, true),
  ('ve012', 'Klyntar Symbiote', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/012.png', 10, 0, true),
  ('ve013', 'Spider-Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/013.png', 10, 0, true),
  ('ve014', 'Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/014.png', 10, 0, true),
  ('ve014b', 'Eganrac', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/014b.png', 10, 0, true),
  ('ve015', 'Sleeper', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/015.png', 10, 0, true),
  ('ve016', 'Eddie Brock', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/016.png', 10, 0, true),
  ('ve017', 'Venomized Jeff the Land Shark', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/017.png', 10, 0, true),
  ('ve018', 'Mac Gargan', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/018.png', 10, 0, true),
  ('ve019', 'Lizard', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/019.png', 10, 0, true),
  ('ve020', 'Spider-Man 2', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/020.png', 10, 0, true),
  ('ve021', 'Rex Strickland', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/021.png', 10, 0, true),
  ('ve022', 'Phage', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/022.png', 10, 0, true),
  ('ve023', 'Maniac', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/023.png', 10, 0, true),
  ('ve024', 'Lasher', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/024.png', 10, 0, true),
  ('ve025', 'Sliver', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/025.png', 10, 0, true),
  ('ve026', 'Symbiote Surface', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/026.png', 10, 0, true),
  ('ve027', 'Manhole Cover', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/027.png', 10, 0, true),
  ('ve028', 'Chasm', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/028.png', 10, 0, true),
  ('ve029a', 'Virus', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/029a.png', 10, 0, true),
  ('ve029b', 'Agent Anti-Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/029b.png', 10, 0, true),
  ('ve030', 'Poison Spider-Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/030.png', 10, 0, true),
  ('ve031a', 'Elektra', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/031a.png', 10, 0, true),
  ('ve031b', 'Carnage Elektra', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/031b.png', 10, 0, true),
  ('ve032', 'Venomized Miles Morales', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/032.png', 10, 0, true),
  ('ve033', 'Riot', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/033.png', 10, 0, true),
  ('ve034', 'Pork Grind', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/034.png', 10, 0, true),
  ('ve035', 'Gorr the God Butcher', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/035.png', 10, 0, true),
  ('ve035bt', 'Black Berserker', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/035bt.png', 10, 0, true),
  ('ve036', 'Spider-Boy', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/036.png', 10, 0, true),
  ('ve037', 'Maker', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/037.png', 10, 0, true),
  ('ve037t', 'Symbiote Prototype', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/037t.png', 10, 0, true),
  ('ve038', 'Gwenom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/038.png', 10, 0, true),
  ('ve039', 'Venom''s Axe', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/039.png', 10, 0, true),
  ('ve040', 'All-Blood the Necrospear', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/040.png', 10, 0, true),
  ('ve041', 'Poison Doom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/041.png', 10, 0, true),
  ('ve042', 'Iron Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/042.png', 10, 0, true),
  ('ve043', 'Poison Captain America', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/043.png', 10, 0, true),
  ('ve044', 'Malekith', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/044.png', 10, 0, true),
  ('ve045', 'Meridius', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/045.png', 10, 0, true),
  ('ve046', 'Lasher', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/046.png', 10, 0, true),
  ('ve047a', 'Agony', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/047a.png', 10, 0, true),
  ('ve047b', 'Scream', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/047b.png', 10, 0, true),
  ('ve048', 'Codex', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/048.png', 10, 0, true),
  ('ve049', 'Host Rider', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/049.png', 10, 0, true),
  ('ve050a', 'Scorpion', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/050a.png', 10, 0, true),
  ('ve050b', 'Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/050b.png', 10, 0, true),
  ('ve051', 'Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/051.png', 10, 0, true),
  ('ve052', 'Old Man Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/052.png', 10, 0, true),
  ('ve052bta', 'Ant-Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/052bta.png', 10, 0, true),
  ('ve052btb', 'Venom Rocket', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/052btb.png', 10, 0, true),
  ('ve052btc', 'Wolverine', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/052btc.png', 10, 0, true),
  ('ve053', 'Poison Thanos', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/053.png', 10, 0, true),
  ('ve054', 'Venomized Phoenix Force', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/054.png', 10, 0, true),
  ('ve055', 'Hybrid', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/055.png', 10, 0, true),
  ('ve056', 'Carnage, God of Symbiotes', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/056.png', 10, 0, true),
  ('ve056bt', 'Symbiote', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/056bt.png', 10, 0, true),
  ('ve057', 'Loki the All-Butcher', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/057.png', 10, 0, true),
  ('ve058', 'Spider-Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/058.png', 10, 0, true),
  ('ve058bt', 'Arachniote', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/058bt.png', 10, 0, true),
  ('ve059', 'Knull', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/059.png', 10, 0, true),
  ('ve060', 'Klyntar', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/060.png', 10, 0, true),
  ('ve099', 'Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/099.png', 10, 0, true),
  ('ve099bt', 'Viper', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/099bt.png', 10, 0, true),
  ('ve100', 'Spider-Man', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/100.png', 10, 0, true),
  ('ve101', 'Carnage', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/101.png', 10, 0, true),
  ('ve200', 'Venom Horse', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/200.png', 10, 0, true),
  ('ve201', 'Venom T-Rex', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/201.png', 10, 0, true),
  ('veL023', 'Venom, Space Knight', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L023.png', 10, 0, true),
  ('veL025', 'Anti-Venom', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L025.png', 10, 0, true),
  ('veL029', 'Demogoblin', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L029.png', 10, 0, true),
  ('veL038', 'Carrion', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L038.png', 10, 0, true),
  ('veL048', 'Shriek', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L048.png', 10, 0, true),
  ('veL053a', 'Doppelganger', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L053a.png', 10, 0, true),
  ('veL054', 'Venom Iceman', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L054.png', 10, 0, true),
  ('veL056', 'Venom Captain Marvel', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/L056.png', 10, 0, true),
  ('veM001', 'Island Prison', null, 10, 0, true),
  ('veM002', 'Klyntar', null, 10, 0, true),
  ('veM003', 'Life Foundation Lab', null, 10, 0, true),
  ('veM004', 'Lombard Street (Venomized)', null, 10, 0, true),
  ('veOS001', 'Separation Anxiety', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS001.jpg', 10, 0, true),
  ('veOS002', 'Lethal Protector', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS002.jpg', 10, 0, true),
  ('veOS003', 'Maximum Carnage', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS003.jpg', 10, 0, true),
  ('veOS004', 'Concealed Costume', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS004.jpg', 10, 0, true),
  ('veOS005', 'Alien Hunger', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS005.jpg', 10, 0, true),
  ('veOS006', 'Alpha-Magni Illuminizor', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS006.jpg', 10, 0, true),
  ('veOS007', 'Into The Venomverse', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS007.jpg', 10, 0, true),
  ('veOS008', 'The Enemy Within', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS008.jpg', 10, 0, true),
  ('veOS009', 'Double Trouble', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS009.jpg', 10, 0, true),
  ('veOS010', 'Let There Be Carnage', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS010.jpg', 10, 0, true),
  ('veOS011', 'Life Foundation', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS011.jpg', 10, 0, true),
  ('veOS012', 'Zombiote Infection', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS012.jpg', 10, 0, true),
  ('veOS013', 'Hive Incursion', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS013.jpg', 10, 0, true),
  ('veOS014', 'Ravencroft Institute', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS014.jpg', 10, 0, true),
  ('veOS015', 'Venomize', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS015.jpg', 10, 0, true),
  ('veOS016', 'Sewer Retreat', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/OS016.jpg', 10, 0, true),
  ('veTM001', 'Alien Vine (A)', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/TM001.png', 10, 0, true),
  ('veTM002', 'Alien Vine (B)', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/TM002.png', 10, 0, true),
  ('veTM003', 'Tendril', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/TM003.jpg', 10, 0, true),
  ('veTM004', 'Alien Plant', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/TM004.jpg', 10, 0, true),
  ('veTM005', 'Stone', 'https://storage.googleapis.com/static.hcunits.net/images/set/ve/TM005.jpg', 10, 0, true)
on conflict (product_code) do update
set
  product_name = excluded.product_name,
  image_url = excluded.image_url,
  available_quantity = 10,
  reserved_quantity = 0,
  is_active = true,
  updated_at = timezone('utc', now());

delete from public.product_inventory
where product_code not in (
  've001', 've002', 've003', 've004', 've005', 've006', 've007', 've008', 've009', 've010',
  've011', 've012', 've013', 've014', 've014b', 've015', 've016', 've017', 've018', 've019',
  've020', 've021', 've022', 've023', 've024', 've025', 've026', 've027', 've028', 've029a',
  've029b', 've030', 've031a', 've031b', 've032', 've033', 've034', 've035', 've036', 've037',
  've038', 've039', 've040', 've041', 've042', 've043', 've044', 've045', 've046', 've047a',
  've047b', 've048', 've049', 've050a', 've050b', 've051', 've052', 've053', 've054', 've055',
  've056', 've057', 've058', 've059', 've060', 'veL023', 'veL025', 'veL029', 'veL038', 'veL048',
  'veL053a', 'veL054', 'veL056', 'veOS001', 'veOS002', 'veOS003', 'veOS004', 'veOS005', 'veOS006',
  'veOS007', 'veOS008', 'veOS009', 'veOS010', 'veOS011', 'veOS012', 'veOS013', 'veOS014', 'veOS015',
  'veOS016'
);
